test

diff --git a/.github/workflows/nucliadb.yml b/.github/workflows/nucliadb.yml
--- a/.github/workflows/nucliadb.yml
+++ b/.github/workflows/nucliadb.yml
@@ -79,10 +79,11 @@ jobs:
           COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
           BRANCH: ${{ steps.git.outputs.branch }}
           MATURIN: "true"
-        run: |
-          ./scripts/download-build.sh && pip install builds/wheels/*_x86_64.whl || (
-            echo "Failed building from the build server." && make build-node-binding-debug
-          )
+        run: make build-node-binding-debug
+        # run: |
+        #   ./scripts/download-build.sh && pip install builds/wheels/*_x86_64.whl || (
+        #     echo "Failed building from the build server." && make build-node-binding-debug
+        #   )
 
       - name: Run tests
         # These tests can be flaky, let's retry them...
